function Get-CostInfo {
    <# =========================================================================
    .DESCRIPTION
        This function looks for the presence of the price data csv file
        generated by Get-AWSPriceData and fills in values for the provided list of
        EC2 instances.
    .EXAMPLE
        PS C:\> Get-CostInfo
    .PARAMETER InstanceList
        blah
    .PARAMETER Region
        blah
    ========================================================================= #>
    Param(
        [System.Object[]] $InstanceList, # [EC2Instance[]]
        
        [ValidateSet('us-east-1','us-east-2','us-west-1','us-west-2')]
        [string] $Region
    )
    $DataFile = "$env:ProgramData\AWS\AmazonEC2_PriceData.csv"
    if ( -not ( Test-Path $DataFile ) ) { Get-AWSPriceData }

    $PriceInfo = Import-Csv -Path $DataFile | Where-Object Location -eq $RegionTable[$Region]
    foreach ( $instance in $InstanceList ) {
        foreach ( $price in $PriceInfo ) {
            if ( ( $instance.Type -eq $price.'Instance Type' ) -and ( $price.TermType -eq 'OnDemand' ) ) {
                [double]$ODP = [math]::Round($price.PricePerUnit,3)
                $instance.OnDemandPrice = [math]::Round( $ODP * 24 * 365 )
            }
            if ( ( $instance.Type -eq $price.'Instance Type' ) -and ( $price.TermType -eq 'Reserved' ) ) {
                $instance.ReservedPrice = $price.PricePerUnit
            }
        }
        $instance.Savings = ( 1 - ( $instance.ReservedPrice / $instance.OnDemandPrice ) ).ToString("P")
    }
    $InstanceList
}
