name: ci
run-name: ci

on:
  pull_request:
    branches: ["*"]
  push:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    uses: jjohns-dev/pwsh-module-ci/.github/workflows/ci.yml@v1
    with:
      os-matrix: '["ubuntu-latest"]'
    permissions:
      contents: read
      checks: write
