name: validate
run-name: validate

on:
  pull_request:
    branches: ["*"]
    #paths-ignore:
      #- README.md
      #- CONTRIBUTING.md
      #- .gitignore
      #- .github/**

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # checkout code

      - shell: pwsh # install dependencies
        run: .\Build\build.ps1 -ResolveDependency -TaskList 'Init'

      - shell: pwsh # stage module
        run: .\Build\build.ps1 -TaskList 'CombineFunctionsAndStage'

      - shell: pwsh # psscriptanalyzer
        run: .\Build\build.ps1 -TaskList 'Analyze'

      - shell: pwsh # pester
        run: .\Build\build.ps1 -TaskList 'Test'

      - uses: actions/upload-artifact@v4 # publish pester results
        with:
          name: Pester Results
          path: "Artifacts/**/Test-*.xml"
          if-no-files-found: error
